spring:
  application:
    name: finance-dashboard
  
  datasource:
    url: jdbc:h2:mem:financedb
    driver-class-name: org.h2.Driver
    username: sa
    password: ${DB_PASSWORD:}
  
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

app:
  cors:
    allowed-origins: http://localhost:3000
  jwtSecret: bXlTZWNyZXRLZXlGb3JGaW5hbmNlRGFzaGJvYXJkVmVyeVNlY3VyZUFuZExvbmdLZXlUaGF0SXNBdExlYXN0MjU2Qml0c0xvbmc=
  jwtExpirationMs: 86400000

logging:
  level:
    com.finance.dashboard: DEBUG
    org.springframework.web: DEBUG
